{{- if .Values.certificate.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls
  namespace: istio-ingress
spec:
  secretName: {{ .Release.Name }}-tls
  commonName: {{ .Values.hostname }}
  dnsNames:
    - {{ .Values.hostname }}
  duration: 168h
  renewBefore: 24h
  issuerRef:
    {{- if eq .Values.certificate.issuer "cloudflare" }}
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: prod-issuer
    {{- else }}
    name: {{ .Values.certificate.issuer | default "cloudflare" }}
    {{- end }}
{{- end }}